export type Place = {
  id: string;
  name: string;
  category: "Food" | "Activities";
  tag: string;
  description: string;
  address: string;
  emoji: string;
  color: string;
  source: string;
  tip: string;
  audience: string[];
  kind: string;
  area: string;
  cost: string;
  duration: string;
  checked: string;
  highlights: string[];
  booking?: string;
  review?: { publisher: string; url: string; text: string; date?: string };
  steps?: { title: string; detail: string; placeId: string }[];
};
export const places: Place[] = [
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Hawker",
    cost: "Pay per order",
    duration: "30–45 min",
    highlights: [
      "Try the char siew or prawn rice rolls.",
      "Add a little chilli; taste the soy dressing first.",
    ],
    id: "pin-wei",
    name: "Pin Wei Chee Cheong Fun",
    category: "Food",
    tag: "A breakfast worth waking up for",
    description:
      "Silky rice rolls, steamed to order. Start your Pek Kio food adventure with this much-loved hawker classic.",
    address: "41A Cambridge Road, #01-25",
    emoji: "🥢",
    color: "peach",
    source:
      "https://cnalifestyle.channelnewsasia.com/dining/best-local-food-singapore-chee-cheong-fun-pek-kio-pin-wei-256311",
    tip: "Try a morning visit. Stalls can sell out, so check opening hours before heading over.",
    review: {
      publisher: "CNA Lifestyle",
      url: "https://cnalifestyle.channelnewsasia.com/dining/best-local-food-singapore-chee-cheong-fun-pek-kio-pin-wei-256311",
      text: "Denise Tan praised the delicate rice rolls and the care that goes into steaming each order.",
      date: "2020-02-20",
    },
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Hawker",
    cost: "Pay per order",
    duration: "30–45 min",
    highlights: [
      "Choose soup or dry noodles.",
      "Ask which prawn sizes are available and confirm the price before ordering.",
    ],
    id: "wah-kee",
    name: "Wah Kee Big Prawn Noodles",
    category: "Food",
    tag: "Old-school, big flavour",
    description:
      "A longtime Pek Kio institution known for its prawn broth and generous sea prawns. One for your local food list.",
    address: "41A Cambridge Road, #01-15",
    emoji: "🍜",
    color: "yellow",
    source:
      "https://cnalifestyle.channelnewsasia.com/dining/wah-kee-big-prawn-noodles-reopens-after-3-month-closure-583786",
    tip: "CNA reported a planned June 2026 reopening. Confirm current hours with the stall before visiting.",
    review: {
      publisher: "CNA Lifestyle",
      url: "https://cnalifestyle.channelnewsasia.com/dining/wah-kee-big-prawn-noodles-reopens-after-3-month-closure-583786",
      text: "The stall is known for sea prawns and prawn-oil broth. The 2026 profile also discusses differing views on value and service.",
      date: "2026-05-29",
    },
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Hawker",
    cost: "Pay per order",
    duration: "30–45 min",
    highlights: [
      "Make a breakfast circuit before choosing your stall.",
      "Pick up fresh market essentials on the same trip.",
    ],
    id: "market",
    name: "Pek Kio Market & Food Centre",
    category: "Food",
    tag: "The heart of the neighbourhood",
    description:
      "Follow your appetite through the stalls, pick up market essentials, and settle into the rhythm of a local morning.",
    address: "41A Cambridge Road, Singapore 211041",
    emoji: "☕",
    color: "mint",
    source: "https://sethlui.com/pek-kio-market-food-centre-food-guide/",
    tip: "Bring some cash, return your tray, and leave a little room to try something new.",
    review: {
      publisher: "Eatbook",
      url: "https://eatbook.sg/pek-kio-food/",
      text: "The 2025 guide covers both well-known stalls and everyday meals at the refreshed food centre.",
      date: "2025-01-15",
    },
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Hawker",
    cost: "Pay per order",
    duration: "30–45 min",
    highlights: [
      "Try dry prawn mee with soup on the side.",
      "Ask about pork rib or pork trotter add-ons.",
    ],
    id: "lai-hiang",
    name: "Lai Hiang Pork Rib Prawn Mee",
    tag: "Prawn mee with a loyal following",
    description:
      "Springy noodles, chilli and a comforting prawn broth make this a satisfying breakfast or early lunch.",
    address: "41A Cambridge Road, #01-41",
    source: "https://eatbook.sg/lai-hiang-pork-rib-prawn-mee/",
    review: {
      publisher: "Eatbook",
      url: "https://eatbook.sg/lai-hiang-pork-rib-prawn-mee/",
      text: "The June 2026 review liked the chilli, noodles and soup; it also noted early sell-outs and just one prawn in the smallest bowl.",
      date: "2026-06-29",
    },
    tip: "Go early and check the day’s menu. Eatbook reported a small bowl from S$2.50 in June 2026; prices and portions can change.",
    category: "Food",
    emoji: "🍽️",
    color: "peach",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Hawker",
    cost: "Pay per order",
    duration: "30–45 min",
    highlights: [
      "Try the fried Hokkien mee.",
      "Prefer drier noodles? This stall’s wetter style may not be your first choice.",
    ],
    id: "sheng-seng",
    name: "Sheng Seng Fried Prawn Noodles",
    tag: "For the wet-style Hokkien mee fans",
    description:
      "A plate of saucy Hokkien mee with prawns, squid and fishcake. Pair it with a little lime and sambal.",
    address: "41A Cambridge Road, #01-40",
    source: "https://danielfooddiary.com/2019/04/05/shengseng/",
    review: {
      publisher: "Google reviews via Wanderlog",
      url: "https://wanderlog.com/place/details/1070288/sheng-seng-fried-prawn-noodles",
      text: "Opinions are mixed: some enjoy the broth, while others prefer more wok hei or a drier texture.",
    },
    tip: "Check recent reviews and opening days before a special trip. Older guides list different hours.",
    category: "Food",
    emoji: "🍽️",
    color: "peach",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Snacks & drinks",
    cost: "Pay per order",
    duration: "10–15 min",
    highlights: [
      "Look for the peanut pancake.",
      "Ask whether the crisp pancake option is available.",
    ],
    id: "yean-heng",
    name: "Yean Heng Pancake",
    tag: "A little sweet finish",
    description:
      "Traditional min jiang kueh with peanut, coconut and other fillings. A handy takeaway treat after your market breakfast.",
    address: "41A Cambridge Road, #01-32",
    source: "https://eatbook.sg/yean-heng-pancake/",
    review: {
      publisher: "Burpple community",
      url: "https://www.burpple.com/yean-heng-pancake/reviews",
      text: "Reviewers mention crisp edges and a chewy centre, with mixed views on filling intensity; several recommend eating them warm.",
    },
    tip: "Choose from what is freshly available. Popular batches may sell out.",
    category: "Food",
    emoji: "🍽️",
    color: "peach",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Hawker",
    cost: "Pay per order",
    duration: "30–45 min",
    highlights: [
      "Try the white or black carrot cake.",
      "Ask whether a mixed plate is available if you are sharing.",
    ],
    id: "good-spice",
    name: "Good Spice Carrot Cake",
    tag: "Black, white, or a bit of both",
    description:
      "Fried radish cake with egg and preserved radish. Choose white for a savoury plate or black for the dark-sauce version.",
    address: "41A Cambridge Road, #01-20",
    source: "https://www.burpple.com/good-spice-carrot-cake",
    review: {
      publisher: "Burpple community",
      url: "https://www.burpple.com/good-spice-carrot-cake",
      text: "Reviews vary: some appreciate the egg and dark sauce, while others find the white version rather mild.",
    },
    tip: "Decide whether you prefer a softer, eggy style. Check today’s price on the stall menu.",
    category: "Food",
    emoji: "🍽️",
    color: "peach",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Snacks & drinks",
    cost: "Pay per order",
    duration: "10–15 min",
    highlights: [
      "Try soya bean milk.",
      "Ask for a soya-bean-and-grass-jelly mix.",
    ],
    id: "min-hiang",
    name: "Min Hiang",
    tag: "Your hawker-lunch cool-down",
    description:
      "Soya bean milk and grass jelly drinks for a simple, cooling pause between stalls.",
    address: "41A Cambridge Road, #01-21",
    source: "https://sethlui.com/pek-kio-market-food-centre-food-guide/",
    review: {
      publisher: "SETHLUI.com",
      url: "https://sethlui.com/pek-kio-market-food-centre-food-guide/",
      text: "The review highlighted creamy soya bean milk and a refreshing grass jelly drink.",
      date: "2019-06-27",
    },
    tip: "Ask about sweetness and ice when ordering.",
    category: "Food",
    emoji: "🍽️",
    color: "peach",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Hawker",
    cost: "Pay per order",
    duration: "30–45 min",
    highlights: [
      "Ask which roast meats are available.",
      "Share a mixed-meat order if you want to sample more than one.",
    ],
    id: "cambridge-roast",
    name: "Cambridge Road Hong Kong Roast Pork",
    tag: "A dependable roast-meat lunch",
    description:
      "Roast pork, char siew and duck with rice. A practical pick when everyone at the table wants something familiar.",
    address: "41A Cambridge Road, #01-18",
    source: "https://sethlui.com/pek-kio-market-food-centre-food-guide/",
    review: {
      publisher: "SETHLUI.com",
      url: "https://sethlui.com/pek-kio-market-food-centre-food-guide/",
      text: "The reviewer enjoyed the homely meal and friendly service, without ranking it above every roast-meat stall.",
      date: "2019-06-27",
    },
    tip: "Confirm the price of a mixed order before it is plated.",
    category: "Food",
    emoji: "🍽️",
    color: "peach",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Hawker",
    cost: "Pay per order",
    duration: "30–45 min",
    highlights: [
      "Try nasi lemak with your preferred sides.",
      "Check which economical breakfast options are ready.",
    ],
    id: "sin-kee",
    name: "Sin Kee Nasi Lemak",
    tag: "Coconut rice and your favourite sides",
    description:
      "Build a plate around coconut rice, sambal and fried sides, or ask about the stall’s bee hoon options.",
    address: "41A Cambridge Road, #01-34",
    source: "https://eatbook.sg/pek-kio-food/",
    review: {
      publisher: "Eatbook",
      url: "https://eatbook.sg/pek-kio-food/",
      text: "The guide recommends the fragrant rice and punchy sambal.",
      date: "2025-01-15",
    },
    tip: "Do not assume halal certification from the dish name; check with the stall if this matters to you.",
    category: "Food",
    emoji: "🍽️",
    color: "peach",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Hawker",
    cost: "Pay per order",
    duration: "30–45 min",
    highlights: [
      "Choose your ingredients and ask about the minimum order.",
      "Try the chilli alongside the broth.",
    ],
    id: "cambridge-ytf",
    name: "Cambridge Road Yong Tau Foo",
    tag: "Mix, match, make it yours",
    description:
      "Choose your yong tau foo ingredients and enjoy them with soup or noodles. A flexible alternative to a fixed rice plate.",
    address: "41A Cambridge Road, #01-47",
    source: "https://eatbook.sg/pek-kio-food/",
    review: {
      publisher: "Eatbook",
      url: "https://eatbook.sg/pek-kio-food/",
      text: "The guide highlights handmade ingredients and a lighter broth.",
      date: "2025-01-15",
    },
    tip: "Ask for the current per-piece price and minimum order before choosing.",
    category: "Food",
    emoji: "🍽️",
    color: "peach",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Cafés",
    cost: "Café menu prices",
    duration: "45–75 min",
    highlights: [
      "Try a bottled cold brew or ask about the current coffee selection.",
      "Browse the brunch menu before choosing a main.",
    ],
    id: "old-hen",
    name: "Old Hen Coffee · Owen Road",
    tag: "Brunch with your favourite people",
    description:
      "A neighbourhood café for cold brew, coffee and a leisurely brunch. Good for an unhurried catch-up along Owen Road.",
    address: "127 Owen Road, Singapore 218931",
    source: "https://www.oldhencoffee.com/",
    review: {
      publisher: "Old Hen Coffee",
      url: "https://www.oldhencoffee.com/",
      text: "The café’s own site presents its Owen Road outlet as a brunch spot and provides its current menu and reservation links.",
    },
    tip: "This listing is for Owen Road, not the former Rangoon Road café. Check the official menu and reservations.",
    category: "Food",
    emoji: "🍽️",
    color: "peach",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Cafés",
    cost: "Café menu prices",
    duration: "45–70 min",
    highlights: [
      "Browse the current brunch menu.",
      "Ask which tiramisu flavours are on today.",
    ],
    id: "syip",
    name: "SYIP · Farrer Park",
    tag: "Brunch, coffee, a little tiramisu",
    description:
      "An Owen Road café for a slower brunch and dessert break. Come with a friend and leave room for tiramisu.",
    address: "79 Owen Road, Singapore 218895",
    source:
      "https://www.timeout.com/singapore/restaurants/50-best-cafes-singapore",
    review: {
      publisher: "Time Out Singapore",
      url: "https://www.timeout.com/singapore/restaurants/50-best-cafes-singapore",
      text: "The June 2026 guide recommends the brunch dishes and signature tiramisu, and notes a peak-hour dining limit.",
      date: "2026-06-05",
    },
    tip: "Plan a relaxed meal, but check any dining time limit during busy periods.",
    category: "Food",
    emoji: "🍽️",
    color: "peach",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Nearby · Rangoon Road",
    kind: "Cafés",
    cost: "Café menu prices",
    duration: "45–75 min",
    highlights: [
      "Explore the Japanese-Western mains.",
      "Ask about the current soy-based or tea drinks.",
    ],
    id: "daizu",
    name: "Daizu Cafe",
    tag: "A Japanese-Western café detour",
    description:
      "A two-storey café on Rangoon Road with Japanese-influenced mains and coffee. A nearby change of pace from the hawker centre.",
    address: "129 Rangoon Road, Singapore 218407",
    source: "https://www.daizucafe.com/",
    review: {
      publisher: "Time Out Singapore",
      url: "https://www.timeout.com/singapore/restaurants/daizu-cafe-1",
      text: "The review liked the light-filled space and Japanese-Western brunch approach. Its older menu examples may have changed.",
      date: "2020-11-07",
    },
    tip: "Use the café’s current menu or reservation page for today’s dishes and service hours.",
    category: "Food",
    emoji: "🍽️",
    color: "peach",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Outdoors",
    cost: "Free to explore",
    duration: "20–40 min",
    highlights: [
      "Take a gentle loop through the therapeutic garden.",
      "Bring water and choose a cooler time for a walk.",
    ],
    id: "pek-kio-park",
    name: "Pek Kio Park & therapeutic garden",
    tag: "A green pause close to home",
    description:
      "Follow the garden’s simple loop, enjoy the planting, and take a breather between the neighbourhood’s housing blocks.",
    address: "Pek Kio Park, Cambridge Road",
    source: "https://www.nparks.gov.sg/visit/parks/park-detail/pek-kio-park/",
    tip: "NParks lists the park as open 24 hours and wheelchair accessible. Observe on-site notices and keep paths clear.",
    category: "Activities",
    emoji: "🌿",
    color: "mint",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Creative",
    cost: "Paid session · confirm fee",
    duration: "2½-hour art-jamming offer",
    highlights: [
      "Ask which art-jamming dates are available.",
      "Confirm the venue and materials before attending.",
    ],
    id: "heartroom",
    name: "Art jamming with Heartroom Gallery",
    tag: "Make something that’s yours",
    description:
      "Book a painting session or ask about art classes for adults and young people. A creative option close to Pek Kio.",
    address: "48A Dorset Road, #24-119, Singapore 211048",
    source: "https://heartroomgallery.com/local-art-classes/",
    tip: "The current contact page lists a residential unit; arrange an appointment and confirm the session location rather than walking in.",
    category: "Activities",
    emoji: "🌿",
    color: "mint",
    booking: "https://heartroomgallery.com/product/art-jamming-gift-card/",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Nearby · Farrer Park",
    kind: "Sports",
    cost: "Court booking fees apply",
    duration: "Book a suitable slot",
    highlights: [
      "Find the facility on MyActiveSG+ and book a court.",
      "Bring paddles, balls, suitable shoes and your group.",
    ],
    id: "activesg",
    name: "Pickleball at ActiveSG Courts @ Farrer Park",
    tag: "New courts, new doubles partners",
    description:
      "Eight pickleball courts opened at the Little India Bus Terminal in March 2026. Bring your playing group and book a slot.",
    address: "ActiveSG Courts @ Farrer Park, Little India Bus Terminal",
    source:
      "https://www.sportsingapore.gov.sg/media-centre/activesg-courts---farrer-park-opens--showcasing-creative-space-optimisation-with-bus-terminal-sports-integration/",
    tip: "SportSG lists Monday–Saturday, 9am–9pm. The space resumes bus-terminal use on Sundays; do not plan Sunday play.",
    category: "Activities",
    emoji: "🌿",
    color: "mint",
    booking: "https://activesg.gov.sg/",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Nearby · Little India",
    kind: "Heritage",
    cost: "Admission depends on eligibility",
    duration: "60–90 min",
    highlights: [
      "Browse the permanent galleries.",
      "Check the official calendar for exhibitions or guided tours.",
    ],
    id: "indian-heritage",
    name: "Indian Heritage Centre",
    tag: "A nearby afternoon of discovery",
    description:
      "Explore the stories of Indian and South Asian communities in Singapore, then take a wander around Campbell Lane.",
    address: "5 Campbell Lane, Singapore 209924",
    source: "https://www.indianheritage.gov.sg/en",
    tip: "The centre lists 10am–6pm, closed Mondays, with free admission for Singapore citizens and PRs. Check other ticket categories and special exhibitions.",
    category: "Activities",
    emoji: "🌿",
    color: "mint",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Nearby · Little India",
    kind: "Heritage",
    cost: "Free to explore",
    duration: "60–120 min",
    highlights: [
      "Choose one of the official themed routes.",
      "Use the trail map and stop at places that interest you.",
    ],
    id: "little-india-trail",
    name: "Little India Heritage Trail",
    tag: "Look up. There’s a story there.",
    description:
      "Follow an NHB trail through nearby Little India, exploring historic streets, traditional trades and community landmarks.",
    address: "Indian Heritage Centre, 5 Campbell Lane",
    source: "https://www.roots.gov.sg/nhb/little-india-heritage-trail",
    tip: "This is a self-guided outing. Respect worship spaces, check visiting access, and keep photography to permitted areas.",
    category: "Activities",
    emoji: "🌿",
    color: "mint",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Day plans",
    cost: "Pay for food · park is free",
    duration: "About 90 min",
    highlights: [
      "Start at the hawker centre.",
      "Finish with fresh air close to home.",
    ],
    id: "breakfast-plan",
    name: "Your first Pek Kio morning",
    tag: "A ready-made little adventure",
    description:
      "Breakfast, a drink, then a gentle garden walk. A simple way to get comfortable in your new neighbourhood.",
    address: "Pek Kio Market & Food Centre, 41A Cambridge Road",
    source: "https://www.nparks.gov.sg/visit/parks/park-detail/pek-kio-park/",
    tip: "Suggested itinerary, not a guided event. Allow extra time for queues and change stalls if your first choice is closed.",
    category: "Activities",
    emoji: "🌿",
    color: "mint",
    steps: [
      {
        title: "Start with Pin Wei",
        detail: "Choose a rice-roll breakfast, or another open stall.",
        placeId: "pin-wei",
      },
      {
        title: "Pick up a drink at Min Hiang",
        detail: "Take a short break with soya bean milk or grass jelly.",
        placeId: "min-hiang",
      },
      {
        title: "Unwind at Pek Kio Park",
        detail: "Walk the garden loop at your own pace.",
        placeId: "pek-kio-park",
      },
    ],
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Day plans",
    cost: "Café order + paid art session",
    duration: "About 3–4 hours",
    highlights: [
      "Book the painting session first.",
      "Allow time for a café stop before your appointment.",
    ],
    id: "creative-plan",
    name: "A café-and-canvas afternoon",
    tag: "Make a memory, then make some art",
    description:
      "Pair an Owen Road café stop with a booked Heartroom painting session. A relaxed catch-up with something to take home.",
    address: "Old Hen Coffee, 127 Owen Road",
    source: "https://heartroomgallery.com/product/art-jamming-gift-card/",
    tip: "Suggested itinerary. Confirm the art-session address, duration and availability; meals and activity fees are separate.",
    category: "Activities",
    emoji: "🌿",
    color: "mint",
    steps: [
      {
        title: "Meet at Old Hen",
        detail: "Have coffee and a bite before the session.",
        placeId: "old-hen",
      },
      {
        title: "Head to your Heartroom appointment",
        detail: "Confirm the venue before setting off, then enjoy painting.",
        placeId: "heartroom",
      },
      {
        title: "Save another café for next time",
        detail: "SYIP is another Owen Road option for a future catch-up.",
        placeId: "syip",
      },
    ],
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Sports",
    cost: "Facility booking fees apply",
    duration: "Book a suitable slot",
    highlights: [
      "Book a badminton court or table-tennis room through onePA.",
      "Bring a playing partner, your equipment and water.",
    ],
    id: "badminton",
    name: "Badminton & table tennis at Pek Kio CC",
    category: "Activities",
    tag: "Move · play · meet",
    description:
      "Get your friends together for badminton or table tennis at Pek Kio CC. A good game makes a great icebreaker.",
    address: "Pek Kio CC, 21 Gloucester Road",
    emoji: "🏸",
    color: "lavender",
    source: "https://www.onepa.gov.sg/cc/pek-kio-cc",
    tip: "Check onePA for facility booking, fees and available slots. Equipment and booking are not included.",
  },
  {
    audience: ["Youths"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Creative",
    cost: "Check with organiser",
    duration: "Varies by session",
    highlights: [
      "Ask about the group’s current activities and age eligibility.",
      "Check rehearsal dates before signing up.",
    ],
    id: "arts",
    name: "Pek Kio youth performing arts",
    category: "Activities",
    tag: "For your next side quest",
    description:
      "Explore the MAEC Youth Performing Arts & Cultural Group at Pek Kio CC and discover a different way to connect.",
    address: "Pek Kio CC, 21 Gloucester Road",
    emoji: "🎨",
    color: "peach",
    source:
      "https://www.onepa.gov.sg/interest-groups/maec-youth-performing-arts-cultural-group-i000010496",
    tip: "Contact the organiser for age eligibility, upcoming sessions and how to join.",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Community",
    cost: "Varies by programme",
    duration: "20–30 min introduction",
    highlights: [
      "Ask about upcoming neighbourhood programmes.",
      "Find out where your interests could help as a volunteer.",
    ],
    id: "neighbours",
    name: "Meet the Pek Kio Residents’ Network",
    category: "Activities",
    tag: "A small hello goes a long way",
    description:
      "Get to know Pek Kio Residents’ Network and find out how to take part in neighbourhood life.",
    address: "48 Dorset Road, #01-113",
    emoji: "🌻",
    color: "yellow",
    source: "https://www.onepa.gov.sg/rc/pek-kio-rn",
    tip: "Ask the Residents’ Network about current volunteering and community programmes.",
  },
  {
    audience: ["Youths", "Adults"],
    checked: "2026-09-05",
    area: "Pek Kio",
    kind: "Outdoors",
    cost: "Free to explore",
    duration: "30–45 min",
    highlights: [
      "Start around the market and follow the surrounding public pavements.",
      "Notice the different generations of flats and neighbourhood shops.",
    ],
    id: "heritage",
    name: "Dorset & Cambridge neighbourhood stroll",
    category: "Activities",
    tag: "Slow walks, little discoveries",
    description:
      "Explore Dorset and Cambridge Roads. Pek Kio means “white bridge” in Hokkien — a little clue to the area’s past.",
    address: "Dorset Road, Pek Kio",
    emoji: "🚶",
    color: "mint",
    source:
      "https://www.pa.gov.sg/resource/speeches/speech-by-prime-minister-lee-hsien-loong-at-the-opening-of-pek-kio-cc/",
    tip: "A self-guided neighbourhood stroll, not an organised tour. Bring water and choose a cooler part of the day.",
  },
];
